language: csharp
solution: SampleTravisCI.sln
install:
  - nuget restore SampleTravisCI.sln
  - nuget install NUnit.Runners -Version 3.7.0 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release SampleTravisCI.sln
  - mono ./testrunner/NUnit.Runners.3.7.0/tools/nunit-console.exe ./Calculator.Test/bin/Release/Calculator.Test.dll
