language: csharp
solution: SampleTravisCI.sln
install:
  - nuget restore SampleTravisCI.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
  - nuget install NUnit -Version 3.8.1 -OutputDirectory test
script:
  - xbuild /p:Configuration=Release SampleTravisCI.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./Calculator.Test/bin/Release/Calculator.Test.dll
