language: csharp
solution: SampleTravisCI.sln
install:
  - nuget restore SampleTravisCI.sln
  - nuget install NUnit -Version 3.8.1 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Debug SampleTravisCI.sln
  ./Calculator.Test/bin/Debug/Calculator.Test.dll
